name: smart_banner
description: Display a smart banner on top of the screen of your Flutter Web application.
version: 0.2.1
homepage: https://github.com/TesteurManiak/smart_banner
repository: https://github.com/TesteurManiak/smart_banner
issue_tracker: https://github.com/TesteurManiak/smart_banner/issues
screenshots:
  - description: "Smart banner Android style"
    path: screenshots/android_style.png
  - description: "Smart banner iOS style"
    path: screenshots/ios_style.png

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7

dev_dependencies:
  fd_lints: ^1.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/background.png
